site_name: Projexa LMS Docs
site_url: https://docs.projexa.ai
theme:
  favicon: assets/favicon.svg
  name: material
  logo: https://cdn.projexa.ai/projexa-logo.svg
  palette:
    primary: "#186444"
  features:
    - navigation.sections
    - search.highlight
    - search.suggest
    - toc.integrate
  language: en
  version:
    provider: mike
    selector: true
copyright: "© 2025 Projexa LMS. All rights reserved."
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ProjexaLMS
extra_css:
  - css/custom.css
extra_javascript:
  - "https://insights.projexa.ai/js/script.file-downloads.hash.outbound-links.pageview-props.tagged-events.js"  # External Plausible Analytics script
  - javascripts/extra.js  # Custom JavaScript file to initialize Plausible
nav:
  - Introduction: index.md
  - How to Onboard:
      - Getting Started: how-to-onboard.md
      - Microsoft OAuth Authentication: how-to-onboard-microsoft.md
      - Magic Link Authentication: how-to-onboard-magic.md
  - Idea Submission:
      - Submitting Ideas: idea-submission.md
  - Team:
      - Team Creation: team-management.md
      - Team Interaction: team-interaction.md
      - Team Evaluation: team-evaluation.md
  - Mentor:
      - Handling Interactions: handling-interactions.md
