site_name: Projexa LMS Docs
site_url: https://docs.projexa.ai
theme:
  favicon: assets/favicon.svg
  name: material
  logo: https://cdn.projexa.ai/projexa-logo.svg
  palette:
    primary: "#186444"
  features:
    - navigation.sections
    - search.highlight
    - search.suggest
    - toc.integrate
  language: en
  version:
    provider: mike
    selector: true
copyright: "© 2025 Projexa LMS. All rights reserved."
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ProjexaLMS
  # Add the custom tracking script here
  javascripts:
    - https://insights.projexa.ai/js/script.file-downloads.hash.outbound-links.pageview-props.tagged-events.js
  # Tracking script (for Plausible Analytics)
  extra_javascript:
    - |
        window.plausible = window.plausible || function() { 
            (window.plausible.q = window.plausible.q || []).push(arguments) 
        }

extra_css:
  - css/custom.css
nav:
  - Introduction: index.md
  - How to Onboard:
      - Getting Started: how-to-onboard.md
      - Microsoft OAuth Authentication: how-to-onboard-microsoft.md
      - Magic Link Authentication: how-to-onboard-magic.md
  - Idea Submission:
      - Submitting Ideas: idea-submission.md
  - Team:
      - Team Creation: team-management.md
